# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pTpBycZAb_WeK1yv6H_Z_ALf6lRqvGWK
"""

#Necessary imports
import argparse
import os
import sys
import numpy as np
from skimage.io import imread
import matplotlib.pyplot as plt
from skimage import color

#read file from path
def loadImg(path):
  img1 = imread(path)

#Plotting the image
def showImg(img1):
  fig,ax = plt.subplots(figsize=(10,10))
  ax.imshow(img1)
  plt.show()



def obtainColor(colr):
  if colr not in color_:
    print(f"{colr} is not in color dictionary so default value is used")
    a,b_min,b_max,c_min,c_max = (0,-25,25,-30,30)
  else:
    a,b_min,b_max,c_min,c_max = color_[colr]
  img = np.copy(img1)
  for i in range(x):
    for j in range(y):
      if lab_img1[i,j][0] > a and \
        lab_img1[i,j][1] > b_min and lab_img1[i,j][1] < b_max and\
        lab_img1[i,j][2] > c_min and lab_img1[i,j][2] < c_max:
        pass
      else:
        img[i,j] = [255,255,255]

  return img

#Plotting all the colors in the given image
def obtainDifferentSegments(img1):
  lab = color.rgb2lab(img1)
  fig,ax = plt.subplots(figsize=(10,10),nrows=3,ncols=2)
  ax[0][0].imshow(obtainColor('pink'))
  ax[0][0].set_title('pink')
  ax[0][1].imshow(obtainColor('red'))
  ax[0][1].set_title('red')
  ax[1][0].imshow(obtainColor('yellow'))
  ax[1][0].set_title('yellow')
  ax[1][1].imshow(obtainColor('blue'))
  ax[1][1].set_title('blue')
  ax[2][0].imshow(obtainColor('white'))
  ax[2][0].set_title('white')
  ax[2][1].imshow(obtainColor('green'))
  ax[2][1].set_title('green')
  plt.show()

if __name__=='__main__':
  parser = argparse.ArgumentParser(description='Path to the image')
  parser.add_argument('--Path',type=str,help='the path to the image',required=True)
  parser.add_argument('--Color',required=False,help='type the color segment you wish to see as string')
  
  args = parser.parse_args()
  path = args.Path
  print(path)
#  if not os.path.isdir(path):
#    print('Given path doesn\'t exist')
#    sys.exit()
  img1 = imread(path)
  lab_img1 = color.rgb2lab(img1)
  x,y,z = lab_img1.shape
  color_ = {'yellow':(70, -50, 0, 30, 100),
		     'red':(30, 25, 100, 0, 100),
		     'green':(50, -128, -20, 0, 50),
		     'blue':(50,-40, 30, -128, -20),
		     'white':(93, -25, 25, -25, 25),
		     'pink':(50, 20,128,-50,0)
         }
  obtainDifferentSegments(imread(path))  
  
  if args.Color:
    showImg(obtainColor(args.Color))
  

